# --------------------------------------------------------------------------
# THIS FILE IS AUTOGENERATED - DO NOT EDIT MANUALLY
#
# Source: Containerfile.j2
# --------------------------------------------------------------------------

ARG BASE_VERSION=15
FROM ghcr.io/daemonless/nginx-base:${BASE_VERSION}

ARG FREEBSD_ARCH=amd64
ARG PACKAGES="ca_root_nss"
ARG UPSTREAM_URL="https://api.github.com/repos/openspeedtest/Docker-Image/releases/latest"
ARG UPSTREAM_JQ=".tag_name"
ARG HEALTHCHECK_ENDPOINT="http://localhost:3005/daemonless-ping"

ENV HEALTHCHECK_URL="${HEALTHCHECK_ENDPOINT}"

# --- Metadata (Injected by Generator) ---
LABEL org.opencontainers.image.title="OpenSpeedTest" \
      org.opencontainers.image.description="Self-hosted HTML5 Network Speed Test on FreeBSD." \
      org.opencontainers.image.source="https://github.com/daemonless/openspeedtest" \
      org.opencontainers.image.url="https://openspeedtest.com/" \
      org.opencontainers.image.documentation="https://github.com/openspeedtest/Speed-Test" \
      org.opencontainers.image.version="dynamic" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.vendor="daemonless" \
      org.opencontainers.image.authors="daemonless" \
      io.daemonless.category="Utilities" \
      io.daemonless.port="3005" \
      io.daemonless.arch="${FREEBSD_ARCH}" \
      io.daemonless.base="nginx" \
      io.daemonless.upstream-url="${UPSTREAM_URL}" \
      io.daemonless.upstream-jq="${UPSTREAM_JQ}" \
      io.daemonless.healthcheck-url="${HEALTHCHECK_ENDPOINT}" \
      io.daemonless.packages="${PACKAGES}"

# Download OpenSpeedTest files (fetch latest release version from Docker-Image repo)
RUN pkg update && pkg install -y ${PACKAGES} jq && \
    VERSION=$(fetch -qo - https://api.github.com/repos/openspeedtest/Docker-Image/releases/latest | jq -r '.tag_name' | sed 's/^v//') && \
    fetch -o /tmp/speedtest.tar.gz "https://api.github.com/repos/openspeedtest/Docker-Image/tarball/v${VERSION}" && \
    mkdir -p /usr/local/www/openspeedtest /app && \
    tar -xzf /tmp/speedtest.tar.gz --strip-components=3 -C /usr/local/www/openspeedtest '*/files/www/*' && \
    rm /tmp/speedtest.tar.gz && \
    echo "${VERSION}" > /app/version && \
    chown -R bsd:bsd /usr/local/www/openspeedtest && \
    pkg delete -y jq && \
    pkg clean -ay && \
    rm -rf /var/cache/pkg/* /var/db/pkg/repos/*

# Copy custom nginx config for OpenSpeedTest
COPY root/ /

RUN chmod +x /etc/cont-init.d/* 2>/dev/null || true

# --- Expose (Injected by Generator) ---
EXPOSE 3005

# --- Volumes (Injected by Generator) ---